# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('threat_level', models.CharField(max_length=25)),
                ('penalty', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CrimesCommitted',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Crime')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('suspect_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('physique', models.CharField(max_length=50)),
                ('complexion', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=50)),
                ('age', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,3}$', message='Invalid Age')])),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('victim_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('cast', models.CharField(max_length=50)),
                ('age', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,3}$', message='Invalid Age')])),
                ('gender', models.CharField(max_length=30)),
                ('complexion', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='crimescommitted',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
        ),
        migrations.AddField(
            model_name='crimescommitted',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Suspect'),
        ),
        migrations.AddField(
            model_name='crimescommitted',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Victim'),
        ),
        migrations.AddField(
            model_name='crime',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CrimeCategory'),
        ),
    ]
