# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_victim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Victim',
        ),
    ]
