# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_victim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('victim_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('cast', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('complexion', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
    ]
