# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_victim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=300)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
