# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161121_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('suspect_id', models.AutoField(primary_key=True, serialize=False)),
                ('physique', models.CharField(max_length=50)),
                ('complexion', models.CharField(max_length=10)),
                ('cast', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
