# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_suspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('threat_level', models.CharField(max_length=50)),
                ('penalty', models.CharField(max_length=50)),
            ],
        ),
    ]
