# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('details', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CrimeCategory')),
            ],
        ),
    ]
