# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_crime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimesCommitted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Crime')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Suspect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Victim')),
            ],
        ),
    ]
