# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_crimescommitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
        ),
    ]
