# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_user_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
