# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_user_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimecategory',
            name='penalty',
            field=models.CharField(choices=[('death', 'Death')], default='Death', max_length=50),
        ),
        migrations.AlterField(
            model_name='crimecategory',
            name='threat_level',
            field=models.CharField(choices=[('high', 'High')], default='High', max_length=50),
        ),
    ]
