# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20161127_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
