# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20161127_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unspecified', 'Cannot Specify')], max_length=10),
        ),
        migrations.AlterField(
            model_name='victim',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unspecified', 'Cannot Specify')], max_length=10),
        ),
    ]
