# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 17:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20161127_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nic',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{13}$')]),
        ),
    ]
