# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 05:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20161127_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{13}$', message='Must be 13 digits')]),
        ),
    ]
