# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 05:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20161128_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', message='Invalid zip code')]),
        ),
    ]
