# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20161128_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('^\\d{11,14}$', message='Invalid Phone Number')]),
        ),
    ]
