# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20161129_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimescommitted',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
