# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20161201_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimecategory',
            name='threat_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=50),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='cast',
            field=models.CharField(choices=[('Punjabi', 'Punjabi'), ('Pashtun', 'Pashtun'), ('Sindhi', 'Sindhi'), ('Seraiki', 'Seraiki'), ('Muhajir', 'Muhajir'), ('Baloch', 'Baloch'), ('Unspecified', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='complexion',
            field=models.CharField(choices=[('Fair', 'Fair'), ('Wheatish', 'Wheatish'), ('Dark', 'Dark')], max_length=10),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='physique',
            field=models.CharField(choices=[('Assault', 'Assault'), ('False Imprisonment', 'False Imprisonment'), ('Kidnapping', 'Kidnapping'), ('Homicide', 'Homicide'), ('Murder', 'Murder'), ('Vehicular Homicide', 'Vehicular Homicide'), ('Rape', 'Rape')], max_length=50),
        ),
        migrations.AlterField(
            model_name='victim',
            name='cast',
            field=models.CharField(choices=[('Punjabi', 'Punjabi'), ('Pashtun', 'Pashtun'), ('Sindhi', 'Sindhi'), ('Seraiki', 'Seraiki'), ('Muhajir', 'Muhajir'), ('Baloch', 'Baloch'), ('Unspecified', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='victim',
            name='complexion',
            field=models.CharField(choices=[('Fair', 'Fair'), ('Wheatish', 'Wheatish'), ('Dark', 'Dark')], max_length=10),
        ),
    ]
